"""Add RecurringTask model and update Task model

Revision ID: 52345a08fbdd
Revises: 1a4bfe3a78a0
Create Date: 2025-10-06 18:36:53.689824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52345a08fbdd'
down_revision: Union[str, None] = '1a4bfe3a78a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_plan_id', sa.Integer(), nullable=False),
    sa.Column('planting_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('recurrence_rule', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['garden_plan_id'], ['garden_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_tasks_id'), 'recurring_tasks', ['id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_task_recurring_task', 'recurring_tasks',
            ['recurring_task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_recurring_task', type_='foreignkey')
        batch_op.drop_column('recurring_task_id')

    op.drop_index(op.f('ix_recurring_tasks_id'), table_name='recurring_tasks')
    op.drop_table('recurring_tasks')
    # ### end Alembic commands ###
