name: Auto Merge Draft PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      # STEP 1: If the PR is a draft, mark it as "Ready for Review"
      - name: 'Mark PR as Ready for Review'
        if: github.event.pull_request.draft == true
        run: gh pr ready ${{ github.event.pull_request.number }} --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # STEP 2: Now that the PR is ready, merge it.
      - name: "Auto-merge"
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          
