name: Auto Merge Draft PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto-merge Drafts"
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_DRAFT: "1"        # ✅ allow merging drafts
          MERGE_LABELS: ""        # no label required
          MERGE_METHOD: "squash"  # or merge/rebase
